### ISSUE TITLE
Lost build orders after upgrade

### ISSUE THREAD

**Issue by StefanoFiumara** [FluffyMaguro/AoE4_Overlay#8]
After upgrading to 1.4.0, the build orders I had saved under the build orders tab have disappeared, I'm curious to know if the storage location of the builds I had written there have changed, and if I can recover the old files after having done the upgrade.

Thanks for the support!

**Comment by FluffyMaguro** [comment]
It seems CraftySalamander changed the key under which buildorders are saved.
I will quickly update the app version to use the old key, but buildorders likely got overwritten if you closed the app.

For me the file where it's stored is 
`C:\Users\Maguro\AppData\Local\AoE4_Overlay\config.json`
In app you can get there by clicking "File\Configs & logs"
If it's already overwritten, Windows might be able to restore it with right click and "Restore previous versions". But that's a stretch.

**Comment by StefanoFiumara** [comment]
Yeah I had already taken a look inside config.json out of curiosity but it appears I did it after closing the app, so my stuff is no longer there, windows says there aren't any previous versions.

Not a huge deal to write them back up, I was just curious to see if it was possible to restore them, thanks for the help

**Comment by CraftySalamander** [comment]
@FluffyMaguro 
Indeed, I changed the key to have naming coherent with the code I copied from my overlay.
I did not think it would cause this issue (in fact, I did not know how these settings and build orders were carried from one release to the next). Sorry for that.

I see you already adapted the code accordingly.
Maybe it would be better to release a version 1.4.1 as soon as possible with these changes, so that people who did not yet update to 1.4.0 will skip it and avoid this issue. Also, if users write new build orders in 1.4.0, it means that when they will update to any later version, they will loose again their build orders.

On top of that, it might be safer for the future to make a copy of the old `config.json` (renaming it for instance `config_current_timestamp.json`) when the app detects that the fields of this JSON file are not up to date with the new format. In such a case, it will be possible for users to still access their lost data.
