### ISSUE TITLE
run from python

### ISSUE THREAD

**Issue by francescodesu** [FluffyMaguro/AoE4_Overlay#9]
Hi

Thank you for your great work!
It works great on windows!

However  I can't get it to run on linux... Do you mind sharing instructions on how to make the program run through python?

Thank you!

**Comment by FluffyMaguro** [comment]
You want to install packages from requirements.txt (I pruned it a bit now). Probably no need to the get the exact same versions of packages. On Windows I'm using the latest packages without issues, only for compiling it matters. 
You also probably want to use a virtual environment, it makes things cleaner. I did have some issues with it on Linux, but that's probably because I am not familiar with Python on Linux.

And then run AoE4_Overlay.py with python (3.6+).
For more specific things on how to do something with Python on Linux, you will need to look for dedicated tutorials on that.
